import type { PluginObj, NodePath } from '@babel/core';
import type * as BabelTypes from '@babel/types';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { loadChonkyConfig, loadPolicyManifest } from './config';
import { isValidRequirementId, generateChonkyId, ensureDir, resolveOutputDir } from './utils';
import type {
  ChonkyConfig,
  PolicyManifest,
  AmbiguityViolation,
  AmbiguityReport,
  RequirementManifest,
  RequirementIndexEntry,
} from './types';

interface PluginOptions {
  projectRoot?: string;
  mode?: 'development' | 'production';
}

interface PluginState {
  opts: PluginOptions;
  filename: string;
  projectRoot: string;
  config: ChonkyConfig;
  mode: string;
  requirementEntries: RequirementIndexEntry[];
  ambiguityViolations: AmbiguityViolation[];
  policyManifest: PolicyManifest | null;
  knownRequirementIds: Set<string>;
}

export function chonkyBabelPlugin(
  { types: t }: { types: typeof BabelTypes },
): PluginObj<PluginState> {
  return {
    name: 'chonky',

    visitor: {
      Program: {
        enter(programPath: NodePath<BabelTypes.Program>, state) {
          const opts = (state.opts ?? {}) as PluginOptions;
          state.filename = state.filename ?? 'unknown';
          state.projectRoot = opts.projectRoot ?? process.cwd();
          state.config = loadChonkyConfig(state.projectRoot);
          state.mode = opts.mode ?? process.env.NODE_ENV ?? 'development';
          state.requirementEntries = [];
          state.ambiguityViolations = [];
          state.knownRequirementIds = new Set<string>();

          const manifestPath =
            state.config.ambiguity?.policyManifest ?? './pm-requirement.json';
          state.policyManifest = loadPolicyManifest(
            manifestPath,
            state.projectRoot,
          );
        },

        exit(_programPath: NodePath<BabelTypes.Program>, state) {
          // --- Ambiguity report generation ---
          if (
            state.config.ambiguity?.generateReport !== false &&
            state.ambiguityViolations.length > 0
          ) {
            const reportPath =
              state.config.ambiguity?.reportPath ??
              '.chonky/ambiguity-report.json';
            const fullReportPath = path.resolve(
              state.projectRoot,
              reportPath,
            );
            ensureDir(path.dirname(fullReportPath));

            const report: AmbiguityReport = {
              timestamp: new Date().toISOString(),
              totalViolations: state.ambiguityViolations.length,
              violations: state.ambiguityViolations,
            };
            fs.writeFileSync(
              fullReportPath,
              JSON.stringify(report, null, 2),
              'utf-8',
            );
          }

          // --- Requirement index generation ---
          if (state.requirementEntries.length > 0) {
            const indexDir = resolveOutputDir(
              state.projectRoot,
              'requirements',
            );
            ensureDir(indexDir);
            const indexPath = path.join(indexDir, 'index.json');

            let existing: RequirementIndexEntry[] = [];
            if (fs.existsSync(indexPath)) {
              try {
                const raw = JSON.parse(fs.readFileSync(indexPath, 'utf-8'));
                existing = raw.requirements ?? [];
              } catch { /* ignore corrupt index */ }
            }

            const merged = mergeIndexEntries(
              existing,
              state.requirementEntries,
            );
            fs.writeFileSync(
              indexPath,
              JSON.stringify(
                {
                  requirements: merged,
                  _chonky: {
                    version: '1.0',
                    generatedAt: new Date().toISOString(),
                  },
                },
                null,
                2,
              ),
              'utf-8',
            );
          }
        },
      },

      // --- 1. defineRequirement visitor ---
      CallExpression(nodePath: NodePath<BabelTypes.CallExpression>, state) {
        const callee = nodePath.node.callee;

        // defineRequirement(...)
        if (t.isIdentifier(callee, { name: 'defineRequirement' })) {
          handleDefineRequirement(t, nodePath, state);
          return;
        }

        // __chonky_assert__(id, scenarios) — generated by preprocessor
        if (t.isIdentifier(callee, { name: '__chonky_assert__' })) {
          handleChonkyAssert(t, nodePath, state);
          return;
        }

        // --- Ambiguity: check api-type excluded items ---
        if (state.policyManifest) {
          checkExcludedApiCall(t, nodePath, state);
        }
      },

      // --- 3. JSX Wrapper visitor ---
      JSXOpeningElement(
        nodePath: NodePath<BabelTypes.JSXOpeningElement>,
        state,
      ) {
        if (state.mode === 'production') return;

        const nameNode = nodePath.node.name;
        let componentName: string;

        if (t.isJSXIdentifier(nameNode)) {
          componentName = nameNode.name;
        } else if (t.isJSXMemberExpression(nameNode)) {
          componentName = getMemberExpressionName(nameNode);
        } else {
          return;
        }

        // Skip wrapping the wrapper itself and HTML intrinsics (lowercase)
        if (componentName === '_ChonkyWrapper') return;

        const relativeFile = path.relative(
          state.projectRoot,
          state.filename,
        );
        const line = nodePath.node.loc?.start.line ?? 0;
        const chonkyId = generateChonkyId(componentName, relativeFile, line);

        nodePath.node.attributes.push(
          t.jsxAttribute(
            t.jsxIdentifier('data-chonky-id'),
            t.stringLiteral(chonkyId),
          ),
        );

        // --- Ambiguity: check component-type excluded items ---
        if (state.policyManifest) {
          checkExcludedComponent(componentName, nodePath, state);
        }
      },

      // --- Ambiguity: check import-type excluded items ---
      ImportDeclaration(
        nodePath: NodePath<BabelTypes.ImportDeclaration>,
        state,
      ) {
        if (!state.policyManifest) return;

        const source = nodePath.node.source.value;

        for (const rule of state.policyManifest.rules) {
          for (const excluded of rule.excluded) {
            if (excluded.type !== 'import') continue;
            if (source === excluded.target || source.startsWith(excluded.target + '/')) {
              reportViolation(state, {
                ruleId: rule.id,
                type: 'excluded',
                target: source,
                file: path.relative(state.projectRoot, state.filename),
                line: nodePath.node.loc?.start.line ?? 0,
                column: nodePath.node.loc?.start.column ?? 0,
                severity: rule.severity ?? (state.config.ambiguity?.strictMode ? 'error' : 'warning'),
              });
            }
          }
        }
      },
    },
  };

  // ========== Handler: defineRequirement ==========

  function handleDefineRequirement(
    t: typeof BabelTypes,
    nodePath: NodePath<BabelTypes.CallExpression>,
    state: PluginState,
  ) {
    const args = nodePath.node.arguments;
    if (args.length === 0 || !t.isObjectExpression(args[0])) return;

    const objExpr = args[0] as BabelTypes.ObjectExpression;

    // Extract the id field
    const idProp = objExpr.properties.find(
      (p): p is BabelTypes.ObjectProperty =>
        t.isObjectProperty(p) &&
        t.isIdentifier(p.key, { name: 'id' }) &&
        t.isStringLiteral(p.value),
    );

    if (!idProp || !t.isStringLiteral(idProp.value)) {
      throw nodePath.buildCodeFrameError(
        '[chonky] defineRequirement() must have a string "id" field.',
      );
    }

    const requirementId = idProp.value.value;

    if (!isValidRequirementId(requirementId)) {
      const msg = `[chonky] Requirement ID "${requirementId}" does not match pattern REQ-<MODULE>-<SEQ>.`;
      if (state.config.verification?.strictBinding) {
        throw nodePath.buildCodeFrameError(msg);
      } else {
        console.warn(msg);
      }
    }

    if (state.knownRequirementIds.has(requirementId)) {
      throw nodePath.buildCodeFrameError(
        `[chonky] Duplicate requirement ID "${requirementId}".`,
      );
    }
    state.knownRequirementIds.add(requirementId);

    // Write manifest JSON
    const relFile = path.relative(state.projectRoot, state.filename);
    const outDir = resolveOutputDir(state.projectRoot, 'requirements');
    ensureDir(outDir);

    const manifest: RequirementManifest = {
      ...(astObjectToPlain(t, objExpr) as unknown as RequirementManifest),
      sourceFile: relFile,
      _chonky: {
        version: '1.0',
        generatedAt: new Date().toISOString(),
      },
    };

    const manifestFile = path.join(outDir, `${requirementId}.json`);
    fs.writeFileSync(manifestFile, JSON.stringify(manifest, null, 2), 'utf-8');

    state.requirementEntries.push({
      id: requirementId,
      sourceFile: relFile,
      manifestPath: `.chonky/requirements/${requirementId}.json`,
    });

    // Replace defineRequirement(obj) → obj (strip wrapper)
    nodePath.replaceWith(objExpr);
  }

  // ========== Handler: __chonky_assert__ ==========

  function handleChonkyAssert(
    t: typeof BabelTypes,
    nodePath: NodePath<BabelTypes.CallExpression>,
    state: PluginState,
  ) {
    const args = nodePath.node.arguments;
    if (args.length < 2) return;
    if (!t.isStringLiteral(args[0])) return;
    if (!t.isArrayExpression(args[1])) return;

    const requirementId = args[0].value;
    const scenariosArray = args[1] as BabelTypes.ArrayExpression;

    const relFile = path.relative(state.projectRoot, state.filename);
    const testDir = path.resolve(
      path.dirname(state.filename),
      '__tests__',
    );
    ensureDir(testDir);
    const testFile = path.join(testDir, `${requirementId}.test.ts`);

    // Build test file content
    const lines: string[] = [
      '/**',
      ' * @chonky-generated',
      ` * @requirement ${requirementId}`,
      ` * @source ${relFile}`,
      ` * @generated-at ${new Date().toISOString()}`,
      ' *',
      ' * WARNING: This file is auto-generated by @chonky/babel-plugin.',
      ' * Do not edit manually. Changes will be overwritten on next build.',
      ' */',
      "import { test, expect, describe } from '@chonky/runtime/test';",
      '',
      `describe('${requirementId}', () => {`,
    ];

    for (const element of scenariosArray.elements) {
      if (!t.isArrayExpression(element) || !element.elements[0]) continue;
      const nameNode = element.elements[0];
      if (!t.isStringLiteral(nameNode)) continue;

      const scenarioName = nameNode.value;
      const fnNode = element.elements[1];
      if (!fnNode) continue;

      const { default: generate } = require('@babel/generator') as typeof import('@babel/generator');
      const fnCode = generate(fnNode).code;
      const isAsync = t.isArrowFunctionExpression(fnNode)
        ? fnNode.async
        : t.isFunctionExpression(fnNode)
          ? fnNode.async
          : false;

      lines.push(
        `  test('${requirementId} | ${scenarioName}', ${isAsync ? 'async ' : ''}${fnCode});`,
      );
      lines.push('');
    }

    lines.push('});');
    lines.push('');

    fs.writeFileSync(testFile, lines.join('\n'), 'utf-8');

    // Remove the __chonky_assert__ call from the source
    const parentPath = nodePath.parentPath;
    if (parentPath?.isExpressionStatement()) {
      parentPath.remove();
    } else {
      nodePath.remove();
    }
  }

  // ========== Ambiguity checks ==========

  function checkExcludedComponent(
    componentName: string,
    nodePath: NodePath<BabelTypes.JSXOpeningElement>,
    state: PluginState,
  ) {
    if (!state.policyManifest) return;

    for (const rule of state.policyManifest.rules) {
      for (const excluded of rule.excluded) {
        if (excluded.type !== 'component') continue;
        if (componentName === excluded.target) {
          reportViolation(state, {
            ruleId: rule.id,
            type: 'excluded',
            target: componentName,
            file: path.relative(state.projectRoot, state.filename),
            line: nodePath.node.loc?.start.line ?? 0,
            column: nodePath.node.loc?.start.column ?? 0,
            severity: rule.severity ?? (state.config.ambiguity?.strictMode ? 'error' : 'warning'),
          });
        }
      }
    }
  }

  function checkExcludedApiCall(
    t: typeof BabelTypes,
    nodePath: NodePath<BabelTypes.CallExpression>,
    state: PluginState,
  ) {
    if (!state.policyManifest) return;

    const callee = nodePath.node.callee;
    let calleeName = '';

    if (t.isIdentifier(callee)) {
      calleeName = callee.name;
    } else if (t.isMemberExpression(callee) && t.isIdentifier(callee.property)) {
      calleeName = callee.property.name;
    }

    if (!calleeName) return;

    for (const rule of state.policyManifest.rules) {
      for (const excluded of rule.excluded) {
        if (excluded.type !== 'api') continue;
        if (calleeName === excluded.target) {
          reportViolation(state, {
            ruleId: rule.id,
            type: 'excluded',
            target: calleeName,
            file: path.relative(state.projectRoot, state.filename),
            line: nodePath.node.loc?.start.line ?? 0,
            column: nodePath.node.loc?.start.column ?? 0,
            severity: rule.severity ?? (state.config.ambiguity?.strictMode ? 'error' : 'warning'),
          });
        }
      }

      // Negate pattern checks on the source text
      if (rule.negate) {
        for (const constraint of rule.negate) {
          const relFile = path.relative(state.projectRoot, state.filename);
          if (constraint.detection.scope) {
            const { minimatch } = requireMinimatch();
            if (!minimatch(relFile, constraint.detection.scope)) continue;
          }

          const regex = new RegExp(constraint.detection.pattern);
          const { default: generate } = require('@babel/generator') as typeof import('@babel/generator');
          const nodeText = generate(nodePath.node).code;
          if (regex.test(nodeText)) {
            reportViolation(state, {
              ruleId: rule.id,
              constraintId: constraint.id,
              type: 'negate',
              behavior: constraint.behavior,
              matchedText: nodeText.slice(0, 100),
              file: relFile,
              line: nodePath.node.loc?.start.line ?? 0,
              column: nodePath.node.loc?.start.column ?? 0,
              severity: rule.severity ?? (state.config.ambiguity?.strictMode ? 'error' : 'warning'),
            });
          }
        }
      }
    }
  }

  function reportViolation(
    state: PluginState,
    violation: AmbiguityViolation,
  ) {
    state.ambiguityViolations.push(violation);

    const prefix =
      violation.severity === 'error' ? '✖ [chonky/ambiguity]' : '⚠ [chonky/ambiguity]';
    const detail =
      violation.type === 'excluded'
        ? `${violation.ruleId}: ${violation.type} "${violation.target}" — ${violation.file}:${violation.line}`
        : `${violation.ruleId}/${violation.constraintId}: negate violated — ${violation.behavior} — ${violation.file}:${violation.line}`;

    if (violation.severity === 'error') {
      throw new Error(`${prefix} ${detail}`);
    } else {
      console.warn(`${prefix} ${detail}`);
    }
  }
}

// ========== Helpers ==========

function getMemberExpressionName(node: BabelTypes.JSXMemberExpression): string {
  const parts: string[] = [];
  let current: BabelTypes.JSXMemberExpression | BabelTypes.JSXIdentifier = node;
  while (current.type === 'JSXMemberExpression') {
    parts.unshift(current.property.name);
    current = current.object;
  }
  if (current.type === 'JSXIdentifier') {
    parts.unshift(current.name);
  }
  return parts.join('.');
}

function astObjectToPlain(
  t: typeof BabelTypes,
  node: BabelTypes.ObjectExpression,
): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const prop of node.properties) {
    if (!t.isObjectProperty(prop)) continue;
    const key = t.isIdentifier(prop.key)
      ? prop.key.name
      : t.isStringLiteral(prop.key)
        ? prop.key.value
        : null;
    if (!key) continue;
    result[key] = astValueToPlain(t, prop.value as BabelTypes.Expression);
  }
  return result;
}

function astValueToPlain(
  t: typeof BabelTypes,
  node: BabelTypes.Expression,
): unknown {
  if (t.isStringLiteral(node)) return node.value;
  if (t.isNumericLiteral(node)) return node.value;
  if (t.isBooleanLiteral(node)) return node.value;
  if (t.isNullLiteral(node)) return null;
  if (t.isArrayExpression(node)) {
    return node.elements.map((el) =>
      el && !t.isSpreadElement(el) ? astValueToPlain(t, el) : null,
    );
  }
  if (t.isObjectExpression(node)) return astObjectToPlain(t, node);
  return undefined;
}

function mergeIndexEntries(
  existing: RequirementIndexEntry[],
  incoming: RequirementIndexEntry[],
): RequirementIndexEntry[] {
  const map = new Map<string, RequirementIndexEntry>();
  for (const e of existing) map.set(e.id, e);
  for (const e of incoming) map.set(e.id, e);
  return Array.from(map.values());
}

function requireMinimatch() {
  try {
    return require('minimatch');
  } catch {
    return {
      minimatch: (file: string, pattern: string) =>
        new RegExp(
          pattern
            .replace(/\*\*/g, '.*')
            .replace(/\*/g, '[^/]*'),
        ).test(file),
    };
  }
}
